### PR TITLE
add kintsugi signed genesis tx

### PR DESCRIPTION
**Pull request by dimiandre**

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Github user https://github.com/dimiandre is not a pilot-100

**Comment by bengtlofgren** [comment]
We expected https://github.com/orgs/kintsugi-tech/people to include https://github.com/dimiandre as a public member. Please update this and ping on discord

**Comment by dimiandre** [comment]
> We expected https://github.com/orgs/kintsugi-tech/people to include https://github.com/dimiandre as a public member. Please update this and ping on discord

done

**Comment by bengtlofgren** [comment]
Github user https://github.com/dimiandre is not a pilot-100

**Pull request merged**
