### PR TITLE
add 0base.vc's toml

### PR DESCRIPTION
**Pull request by jjangg96**

### CODE REVIEW

**Comment by bengtlofgren** [comment]
Github user https://github.com/jjangg96 is not a pilot-100

**Comment by bengtlofgren** [comment]
Github user https://github.com/jjangg96 is not a pilot-100

**Comment by bengtlofgren** [comment]
Github user https://github.com/jjangg96 is not a pilot-100

**Comment by jjangg96** [comment]
> Github user https://github.com/jjangg96 is not a pilot-100

Who should I contact? Something wired. 
I got an e-mail "Shielded Expedition: Pre-genesis Pilots" and I'm in se-100 channel in Discord.

**Comment by jjangg96** [comment]
I made PR again.
https://github.com/anoma/namada-shielded-expedition/pull/96/files

**Pull request closed without merging**
